### ISSUE TITLE
Feature Request: Unlimited results?

### ISSUE THREAD

**Issue by chitgoks** [ugalek/TweetieFeed#2]
Code only shows max of 30 results.

**Comment by ugalek** [comment]
Hello!
You decide how much of a tweet to display by using the URLRequest. Check at the ExampleViewModel.swift getData() function.
For API v1:
`let URLv1 = "https://api.twitter.com/1.1/...&count=30"`
For API v2:
`let URLv2 = "https://api.twitter.com/2/....&max_results=30"`

**Comment by chitgoks** [comment]
@ugalek hi. i see that. what i meant was something like after the 30th tweet is seen, then fetch the next 30 tweets.

or is that how it works already?

**Comment by ugalek** [comment]
@chitgoks Hi! Due to new announcements from Twitter, I am not sure that we will be able to continue using their service :(

**Comment by chitgoks** [comment]
oh no :(

**Comment by ugalek** [comment]
@chitgoks For your question you can try read this https://developer.twitter.com/en/docs/twitter-api/pagination
